### ISSUE TITLE
Color schema is broken

### ISSUE THREAD

**Issue by greshny** [juanpedrojose/ultinvim#1]
Hello

I've tried to install it. And it looks like:

<img width="1280" alt="broken-vim" src="https://cloud.githubusercontent.com/assets/632946/13006224/a28cc836-d187-11e5-889e-a73585fa593c.png">

Any idea how to fix it?

ps: `Iterm build 2.1.4`

**Comment by juanpedrojose** [comment]
The issue is derived from outdated terminals like stable release of iTerm v2.1.4 or even El Capitan's Terminal.app
They do not support 24-bit true color palette.

There are several options:
1. Use latest iTerm betas and NOT using Terminal.app
2. Set `let $NVIM_TUI_ENABLE_TRUE_COLOR` to `0` in `init.vim`

I should probably disable true colors by default for maximum compatibility.

**Comment by greshny** [comment]
> 1. Set let $NVIM_TUI_ENABLE_TRUE_COLOR to 0 in init.vim

it doesn't work

<img width="1280" alt="broken-vim-2" src="https://cloud.githubusercontent.com/assets/632946/13006911/8ec1cfa4-d18c-11e5-895c-d26a81a49683.png">

**Comment by juanpedrojose** [comment]
Please comment line 50 in `init.vim`
or simply pull latest changes.

**Comment by greshny** [comment]
@juanpedrojose 
thanks for quick response. everything is fine now! :+1:
